### ISSUE TITLE
Broken URL in "Your Kippt profile" link icon

### ISSUE THREAD

**Issue by d2s** [kippt/kippt-chrome#23]
Link from extension's icon "Your Kippt profile" points to [missing URL](https://kippt.com/profile) that tells user that "404 Page not found".

Apparently upgrade to new Kippt service broke some of the little details like this one.

Problem is visible on the file: https://github.com/kippt/kippt-chrome/blob/master/extension.html#L20

Few possible fixes for the problem:
- Check if user is logged in and point to right URL with username
- Create redirect on the server that points to right URL (after checking login status)

**Comment by jorilallo** [comment]
I'll have to add that back. Probably pretty useless, I doubt anyone actually uses this really.
